### ISSUE TITLE
[bug] 지도 마커 선택하여 앱크래시됨(로그인 안함)

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_B#106]
## 개요
` 재현경로
`` 로그인하지 않고 실행시 발생
    매물검색에서 삼평동으로 검색 -> 사진 클릭 -> 앱크래시
``

**Comment by HoneyPot8014** [comment]
로그 확인결과, FirebaseAuth의 uid를 사용하는데 확인하지 않고, 사용해서 NPE 에러뜹니다. 
EditText작업할때 같이 진행하겠습니다.

**Comment by lunar999** [comment]
커밋은 따로 쪼개서 해주세요 pr은 하나로 해도 되요
