### ISSUE TITLE
[ UX개선] 홈화면 사용성

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_B#141]
사용법이 어려운거 같아요.
위로 드래그 아래로 드래그 하는 방식이 맞는건가요?

**Comment by sabgilhun** [comment]
주황색 배경 누른 상태에서 위로 땡기면 검색
하얀색 배경 누른 상태에서 아래로 땡기면 글쓰기입니다.

저희도 조금 써보니까 불편한거 같아서 아예 위로 땡기면 검색, 아래로 땡기면 글쓰기로 바꾸려고 합니다
