### ISSUE TITLE
[bug] 지도화면에서 존재하지 않는 데이터가 노출됨

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_B#142]
지도화면에서 삭제 했다고 하는 데이터가 하단에도 나오고 마커로도 보임

확인해보세요

지역을 바꿔도 계속 나오네요

그리고 현재 위치 버튼은 안넣을껀가요?

**Comment by sabgilhun** [comment]
삭제된 데이터 필터링은 아직 맵에서 구현중입니다. 마찬가지로 현재 위치 버튼도 구현 중입니다.

**Comment by pengin7384** [comment]
수정 완료하였습니다. 현재 위치기능은 주말에 구현해보도록 하겠습니다
