### ISSUE TITLE
[bug] 로그인하지 않고 지도화면에서 하단 아이템 선택시 앱크래시

### ISSUE THREAD

**Issue by lunar999** [boostcampth/boostcamp3_B#147]
로그인하지 않고 지도화면에서 하단 아이템 선택시 앱크래시되네요
확인해보세요

**Comment by HoneyPot8014** [comment]
확인했습니다. 로그인하지 않으면 Firebase의 uuid를 못가져와서 NPE 에러 였습니다. 수정했습니다.
